export default [
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/lokesh_coder/128.jpg',
    name: 'Valorant',
    job: 'Direct Security Executive',
    amount: 0.5,
    status: 'distraction',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg',
    name: 'Google Classroom',
    job: 'Forward Accountability Producer',
    amount: 3.5,
    status: 'on-task',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jjsiii/128.jpg',
    name: 'Fornite',
    job: 'Legacy Program Director',
    amount: 4,
    status: 'distraction',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/holdenweb/128.jpg',
    name: 'Canvas',
    job: 'Chief Factors Planner',
    amount: 2,
    status: 'distraction',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/operatino/128.jpg',
    name: 'Naviance',
    job: 'Central Accountability Developer',
    amount: 1.2,
    status: 'distraction',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/akmur/128.jpg',
    name: 'Minecraft',
    job: 'Product Group Architect',
    amount: 5.6,
    status: 'distraction',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/nateschulte/128.jpg',
    name: 'Quizlet',
    job: 'Future Security Planner',
    amount: 3.2,
    status: 'on-task',
    date: 'Mon Oct 28 2019 14:44:31 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jerrybai1907/128.jpg',
    name: 'Minecraft',
    job: 'Direct Brand Specialist',
    amount: 2,
    status: 'distraction',
    date: 'Tue Jul 23 2019 00:24:44 GMT-0300 (Brasilia Standard Time)',
  },
]
